var barrav8 = '';
barrav8 += '<scr'+'ipt language="javascript" type="text/javascript">';
barrav8 += 'function _$getPortal() { if(self != top) { if(top.brturbo) { _$portal = 2; } else if(top.ibest) { _$portal = 3; } else { _$portal = 1; } } else { _$portal = 1; } return _$portal;}';
barrav8 += 'function abrePopGenericoIg(url, largura, altura) { window.open(url, "popgenericoiG", "scrollbars=0, width=" + largura + ", height=" + altura);}';
barrav8 += 'function buscaiG(frm1){ window.open("http://farejador-1.ig.com.br/farejador/search?q="+escape(frm1.q.value)+"&orig=ig_xml_br_web_search_int"); return false;}';
barrav8 += '</scr'+'ipt>';
barrav8 += '<link type="text/css" rel="stylesheet" href="http://image.ig.com.br/homev8/barra/barrav8.css" />';
barrav8 += '<table style="width:100%; height:31px; display:none; background:url(http://image.ig.com.br/hotsites/sites_ig2006/bar_parc_mainbg.jpg) repeat-x;" id="__barra_do_iG__" border="0" cellspacing="0" cellpadding="0">';
barrav8 += '<tr>';
barrav8 += '<td class="barv8_ie">';
barrav8 += '<table style="width:720px; height:31px;" border="0" cellspacing="0" cellpadding="0" class="barv8_fox">';
barrav8 += '<tr>';
barrav8 += '<td><a href="http://www.ig.com.br" target="_parent"><img src="http://image.ig.com.br/hotsites/sites_ig2006/bar_parc_logo_ig.jpg" alt="" width="60" height="31" border="0" /></a></td>';
barrav8 += '<form name="frm1" onSubmit="return buscaiG(this);" style="margin:0; padding:0">';
barrav8 += '<td style="width:25px;"><img src="http://image.ig.com.br/hotsites/sites_ig2006/bar_cxesq.gif" alt="" width="25" height="22" /></td>';
barrav8 += '<td style="background:url(http://image.ig.com.br/hotsites/sites_ig2006/bar_cxmeio.gif) repeat-x;"><input id="q" type="text" name="q" value="Fa&ccedil;a sua busca" onFocus="this.value=\'\'" class="txt_barraigv8_parc" /></td>';
barrav8 += '<td style="width:8px;"><img src="http://image.ig.com.br/hotsites/sites_ig2006/bar_cxdir.gif" alt="" width="8" height="22" /></td>';
barrav8 += '<td><input type="Image" name="Image" src="http://image.ig.com.br/hotsites/sites_ig2006/bar_parc_btnok.jpg" onClick="return buscaiG(this.form);" style="width:34px; height:21px;" /></td>';
barrav8 += '<td><img src="http://image.ig.com.br/hotsites/sites_ig2006/bar_parc_line.jpg" alt="" width="12" height="31" /></td>';
barrav8 += '</form>';
barrav8 += '<td><a href="http://portal.ig.com.br/acesso_internet.html" target="_parent"><img src="http://image.ig.com.br/hotsites/sites_ig2006/bar_parc_btnacess.jpg" alt="" width="60" height="21" border="0" /></a></td>';
barrav8 += '<td><a href="http://portal.ig.com.br/acesso_email.html" target="_parent"><img src="http://image.ig.com.br/hotsites/sites_ig2006/bar_parc_btnmail.jpg" alt="" width="56" height="21" border="0" /></a></td>';
barrav8 += '<td><a href="http://portal.ig.com.br/acesso_cadastrese.html" target="_parent"><img src="http://image.ig.com.br/hotsites/sites_ig2006/bar_parc_btncadstr.jpg" alt="" width="86" height="21" border="0" /></a></td>';
barrav8 += '<td>';
barrav8 += '<select name="select" onChange="parent.location=this.value" class="combo_barraigv8_parc">';
barrav8 += '<option selected>Canais</option>';
barrav8 += '<option value="http://www.voxcards.com.br">Cart&otilde;es</option>';
barrav8 += '<option value="http://babado.ig.com.br">Celebridades</option>';
barrav8 += '<option value="http://igpapo.ig.com.br">Chat</option>';
barrav8 += '<option value="http://iguinho.ig.com.br">Crian&ccedil;as</option>';
barrav8 += '<option value="http://igentretenimento.ig.com.br">Divers&atilde;o</option>';
barrav8 += '<option value="http://www.baixaki.com.br">Downloads</option>';
barrav8 += '<option value="http://www.ig.com.br/paginas/canais/educacao">Educa&ccedil;&atilde;o</option>';
barrav8 += '<option value="http://ultimosegundo.ig.com.br/esportes">Esportes</option>';
barrav8 += '<option value="http://arenaig.ig.com.br">Games</option>';
barrav8 += '<option value="http://delas.ig.com.br">Mulher</option>';
barrav8 += '<option value="http://megaplayer.ig.com.br">Multim&iacute;dia</option>';
barrav8 += '<option value="http://igpop.ig.com.br">M&uacute;sica</option>';
barrav8 += '<option value="http://ultimosegundo.ig.com.br">Not&iacute;cias</option>';
barrav8 += '<option value="http://poupaclique.ig.com.br">Servi&ccedil;os</option>';
barrav8 += '</select>';
barrav8 += '</td>';
barrav8 += '<td><a href="http://www.ibest.com.br" target="_parent"><img src="http://image.ig.com.br/hotsites/sites_ig2006/bar_parc_logo_ibest.jpg" alt="" width="29" height="31" border="0" /></a></td>';
barrav8 += '<td><a href="http://www.brturbo.com.br" target="_parent"><img src="http://image.ig.com.br/hotsites/sites_ig2006/bar_parc_logo_brturbo.jpg" alt="" width="48" height="31" border="0" /></a></td>';
barrav8 += '</tr>';
barrav8 += '</table>';
barrav8 += '</td>';
barrav8 += '</tr>';
barrav8 += '</table>';
barrav8 += '<scr'+'ipt language="javascript" type="text/javascript">';
barrav8 += 'if(_$getPortal() == 1) {';
barrav8 += 'document.getElementById("__barra_do_iG__").style.display = "";';
barrav8 += '}';
barrav8 += '</scr'+'ipt>';
document.write(barrav8);