CONNECT "D:\Projects\ADME4\Dados\Adme.GDB"
USER "SYSDBA" PASSWORD "devkey";
      

ALTER TABLE PRODUTO ADD JUROS		DOUBLE PRECISION;

ALTER TABLE PRODUTO ADD DOLAR    	DOUBLE PRECISION;

ALTER TABLE PRODUTO ADD SEGURO  	DOUBLE PRECISION;

