CONNECT "D:\Projects\ADME4\Dados\Adme.GDB"
USER "SYSDBA" PASSWORD "devkey";
      

ALTER TABLE ANIVERSARIOS ADD AnoNascimento      VARCHAR(4);


ALTER TABLE ANIVERSARIOS ADD DiaMes    		VARCHAR(5);


ALTER TABLE cLIENTE ADD EMAIL          		VARCHAR(100);


ALTER TABLE cLIENTE ADD CPF            		VARCHAR(11);


ALTER TABLE FORNECEDOR ADD EMAIL       		VARCHAR(100);


ALTER TABLE FORNECEDOR ADD CNPJ        		VARCHAR(25);


ALTER TABLE FORNECEDOR ADD Site       		VARCHAR(100);

      

