CONNECT "D:\Projects\ADME4\Dados\Adme.GDB"
USER "SYSDBA" PASSWORD "devkey";

CREATE TABLE METAL (
       CodigoMETAL          INTEGER NOT NULL,
       Descricao            VARCHAR(50),
       PRIMARY KEY (CodigoMetal)
);

CREATE UNIQUE INDEX XPKMETAL ON METAL
(
	CODIGOMETAL
);



ALTER TABLE PRODUTO ADD CodigoMETAL          INTEGER;
ALTER TABLE PRODUTO ADD FOREIGN KEY (CodigoMetal) REFERENCES METAL;


