CONNECT "D:\Projects\ADME4\Dados\Adme.GDB"
USER "SYSDBA" PASSWORD "devkey";

/* Table: ANIVERSARIOS, Owner: SYSDBA */

CREATE TABLE ANIVERSARIOS 
(
  CODIGOCLIENTE	INTEGER NOT NULL,
  NOME	VARCHAR(50) NOT NULL,
  DATA	TIMESTAMP,
 PRIMARY KEY (CODIGOCLIENTE, NOME)
);
ALTER TABLE ANIVERSARIOS ADD FOREIGN KEY (CODIGOCLIENTE) REFERENCES CLIENTE (CODIGOCLIENTE);