CREATE GENERATOR GEN_CODESTACAO;
CREATE GENERATOR GEN_CODUSUARIO;
CREATE GENERATOR GEN_CODPROMOCAO;
CREATE GENERATOR GEN_CODCLIENTE;
CREATE GENERATOR GEN_CODAUTOMACAO;
CREATE GENERATOR GEN_CONLOGCLI;
CREATE GENERATOR GEN_CAIXA;
