insert into REGIAO
(CODIGOREGIAO, DESCRICAO, RESPONSAVEL)
values
(1, 'CUIABA', 'FRANK');

insert into LOJA
(CODIGOLOJA, RAZAOSOCIAL, CODIGOREGIAO, NOMEFANTASIA)
values
(1, 'LAN PARTY', 1, 'Lan Party Jogos em Rede - Shopping 3 Américas');

insert into VALORHORAS
(DIASEMANA, SOCIO15, SOCIO30, SOCIO60)
values
(0, 2, 3, 5);

insert into VALORHORAS
(DIASEMANA, SOCIO15, SOCIO30, SOCIO60)
values
(1, 2, 3, 5);

insert into VALORHORAS
(DIASEMANA, SOCIO15, SOCIO30, SOCIO60)
values
(2, 2, 3, 5);

insert into VALORHORAS
(DIASEMANA, SOCIO15, SOCIO30, SOCIO60)
values
(3, 2, 3, 5);

insert into VALORHORAS
(DIASEMANA, SOCIO15, SOCIO30, SOCIO60)
values
(4, 2, 3, 5);

insert into VALORHORAS
(DIASEMANA, SOCIO15, SOCIO30, SOCIO60)
values
(5, 2, 3, 5);

insert into VALORHORAS
(DIASEMANA, SOCIO15, SOCIO30, SOCIO60)
values
(6, 2, 3, 5);

insert into VALORHORAS
(DIASEMANA, SOCIO15, SOCIO30, SOCIO60)
values
(7, 2, 3, 5);

insert into FERIADO
(DESCRICAO, DIA, MES)
values
('ANO NOVO', 1, 1);

insert into FERIADO
(DESCRICAO, DIA, MES)
values
('DIA DO TRABALHO', 1, 5);

insert into FERIADO
(DESCRICAO, DIA, MES)
values
('INDEPENDÊNCIA DO BRASIL', 7, 9);

insert into FERIADO
(DESCRICAO, DIA, MES)
values
('N. SRA. APARECIDA/CRIANÇAS', 12, 10);

insert into FERIADO
(DESCRICAO, DIA, MES)
values
('NATAL', 25, 12);

insert into FERIADO
(DESCRICAO, DIA, MES)
values
('PROCLAMAÇÃO DA REPÚBLICA', 15, 11);

insert into CLIENTE
(CODIGOLOJA, CODIGOCLIENTE, NOMECOMPLETO, NICKNAME, NOMELOGIN, SENHALOGIN)
values
(1, 1, 'JOSÉ DA SILVA', 'MATRIX', 'JSILVA', '123456');

insert into CLIENTE
(CODIGOLOJA, CODIGOCLIENTE, NOMECOMPLETO, NICKNAME, NOMELOGIN, SENHALOGIN)
values
(1, 2, 'JOÃO DA SILVA', 'HIGHLANDER', 'SILVA', '123456');

SET GENERATOR GEN_CODCLIENTE TO 2;

insert into ESTACAO
(CODIGOLOJA, CODIGOESTACAO, DESCRICAO, IP, ESTADO)
values
(1, 1, 'LP-01', '127.0.0.1', 'A');

insert into ESTACAO
(CODIGOLOJA, CODIGOESTACAO, DESCRICAO, IP, ESTADO)
values
(1, 2, 'LP-02', '127.0.0.2', 'A');

insert into ESTACAO
(CODIGOLOJA, CODIGOESTACAO, DESCRICAO, IP, ESTADO)
values
(1, 3, 'LP-03', '127.0.0.3', 'A');

insert into ESTACAO
(CODIGOLOJA, CODIGOESTACAO, DESCRICAO, IP, ESTADO)
values
(1, 4, 'LP-04', '127.0.0.4', 'A');

insert into ESTACAO
(CODIGOLOJA, CODIGOESTACAO, DESCRICAO, IP, ESTADO)
values
(1, 5, 'LP-05', '127.0.0.5', 'A');

insert into ESTACAO
(CODIGOLOJA, CODIGOESTACAO, DESCRICAO, IP, ESTADO)
values
(1, 6, 'LP-06', '127.0.0.6', 'A');

insert into ESTACAO
(CODIGOLOJA, CODIGOESTACAO, DESCRICAO, IP, ESTADO)
values
(1, 7, 'LP-07', '127.0.0.7', 'A');

insert into ESTACAO
(CODIGOLOJA, CODIGOESTACAO, DESCRICAO, IP, ESTADO)
values
(1, 8, 'LP-08', '127.0.0.8', 'A');

insert into ESTACAO
(CODIGOLOJA, CODIGOESTACAO, DESCRICAO, IP, ESTADO)
values
(1, 9, 'LP-09', '192.168.0.1', 'A');

insert into ESTACAO
(CODIGOLOJA, CODIGOESTACAO, DESCRICAO, IP, ESTADO)
values
(1, 10, 'LP-10', '192.168.0.2', 'A');

SET GENERATOR GEN_CODESTACAO TO 10;
