insert into CLIENTE
(CODIGOLOJA, CODIGOCLIENTE, NOMECOMPLETO, NICKNAME, NOMELOGIN, SENHALOGIN)
values
(1, 1, 'JOSÉ DA SILVA', 'MATRIX', 'JSILVA', '123456');

insert into CLIENTE
(CODIGOLOJA, CODIGOCLIENTE, NOMECOMPLETO, NICKNAME, NOMELOGIN, SENHALOGIN)
values
(1, 2, 'JOÃO DA SILVA', 'HIGHLANDER', 'SILVA', '123456');

SET GENERATOR GEN_CODCLIENTE TO 2;

